### PR TITLE
#584 Fix bug with pipeline discord messages

### LINKED ISSUE #584: [FEATURE] Update deployment messages
## Brief description:
Messages which are being sent to the discord channels lack information about deployment environment and current commit.
Refer to the old messages.

### PR DESCRIPTION
**Pull request by Isak-Bego**
## Changes:
I changed how the content string is built so that it solves the issue of weird indentation. I resolved a syntax error, which was preventing the error message to be shown in the cases of a build failure. 

resolves #584 

## How to verify:

- [ ] Run the deployment script

- [ ] Check the discord channel for the output

### CODE REVIEW

File: deployment.sh [hunk 1]
```diff
@@ -69,13 +71,14 @@ for ((i = 0; i < ${#services[@]}; i++)); do
...
     if [[ "$actual_status" -ne "$expected_status" ]]; then
-        RESULT_STRING="Health check to ${url} failed with status code: ${actual_status}"
+        RESULT_STRING="Health check to $url failed with status code: $actual_status"
+        content='🏗️: '$DEPLOYMENT_ENV$'\n'$COMMIT_TITLE_URL$'\n🚑: Health Check Failed'
 
-        content="🏗️: $DEPLOYMENT_ENV
-        $COMMIT_TITLE_URL
-        ❌: Build Failed"
+        # Use jq to construct the JSON payload properly
+        json_payload=$(jq -n --arg ERR "$RESULT_STRING" --arg CONTENT "$content" \
```
Comment (asynchroza) [inline deployment.sh:78]: jq is not a tool which comes out of the box. You should use something else.

Comment (Isak-Bego) [reply deployment.sh]: I tried to do it manually in the beginning, but it seems to be confusing and error-prone, that's why I used jq. However, check this out. It seems to be working

**Review by asynchroza — APPROVED** [review]
Looks perfect. Thank you for dealing with this pain in the ass string escaping.
